---
core:
  num_workers: 20
logging:
  file: ""
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "/opt/stackstorm/packs/super_cool_python/nornir/hosts.yaml"
    group_file: "/opt/stackstorm/packs/super_cool_python/nornir/groups.yaml"
